server:
  port: 8083
  servlet:
    context-path: /product

spring:
  application:
    name: product-service

  # 👉 Ưu tiên lấy từ ENV SPRING_DATA_MONGODB_URI; nếu không có thì dùng service-name "mongodb"
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@mongodb:27017/product_db?authSource=admin}

  # Upload multipart (cho /update kèm ảnh)
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  kafka:
    bootstrap-servers: ${DBKK_CONNECTION:kafka}:9094
    consumer:
      group-id: product-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  cloud:
    openfeign:
      client:
        config:
          # Timeout mặc định cho tất cả Feign client
          default:
            connect-timeout: 60000
            read-timeout: 120000
          # File-service (đọc từ ENV FEIGN_FILE, fallback sang service-name trong network)
          file-service:
            url: ${FEIGN_FILE:http://file-service:8084/file}
            connect-timeout: 30000
            read-timeout: 60000